### ISSUE TITLE
ModuleNotFoundError: No module named 'custom_nodes.comfyui_controlnet_aux.src.controlnet_aux'

### ISSUE THREAD

**Issue by xlibfly** [TheMistoAI/ComfyUI-Anyline#23]
Traceback (most recent call last):
  File "F:\ComfyUI-aki-v1.1\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-Anyline\__init__.py", line 1, in <module>
    from .anyline import AnyLine
  File "F:\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-Anyline\anyline.py", line 9, in <module>
    from custom_nodes.comfyui_controlnet_aux.src.controlnet_aux.teed import TEDDetector
ModuleNotFoundError: No module named 'custom_nodes.comfyui_controlnet_aux.src.controlnet_aux'

**Comment by UnirionGames** [comment]
Same here

**Comment by hjcxlp** [comment]
same problem

**Comment by RONNYKHALIL** [comment]
+1

**Comment by lellotrek** [comment]
+1

**Comment by Milor123** [comment]
Same issue guys
