### ISSUE TITLE
Is this supposed to work in batches?

### ISSUE THREAD

**Issue by Cedri4** [TheMistoAI/ComfyUI-Anyline#4]
When I try to run multiple images through Anyline I get this error:

!!! Exception during processing!!! operands could not be broadcast together with shapes (16,1280,3,3) (16,1280,2280,3)
Traceback (most recent call last):
  File "F:\Stable-Diffusion\ComfyUI\WorkComfy\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Stable-Diffusion\ComfyUI\WorkComfy\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Stable-Diffusion\ComfyUI\WorkComfy\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 381, in new_func
    res_value = old_func(*final_args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Stable-Diffusion\ComfyUI\WorkComfy\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Stable-Diffusion\ComfyUI\WorkComfy\ComfyUI\custom_nodes\ComfyUI-Anyline\anyline.py", line 62, in get_anyline
    final_result = combine_layers(mteed_result, lineart_result)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Stable-Diffusion\ComfyUI\WorkComfy\ComfyUI\custom_nodes\ComfyUI-Anyline\anyline.py", line 75, in combine_layers
    temp = 1 - (1 - top_layer) * (1 - base_layer)
               ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
ValueError: operands could not be broadcast together with shapes (16,1280,3,3) (16,1280,2280,3)

The width, height and batch numbers of the input is 912x512, 16 images.

**Comment by Cedri4** [comment]
But somehow he found out that the width is 1280 and the height 3.
![image](https://github.com/TheMistoAI/ComfyUI-Anyline/assets/93396286/e00638fa-582e-4cb4-8098-c3db68186dad)

**Comment by Cedri4** [comment]
Also I tried with 1920x1080 images and with 1280x768 but still the same error.

**Comment by xyhStruggler** [comment]
The plugin currently does not support batches. You will have to create Anyline for each image.
Will consider adding this feature later

**Comment by Cedri4** [comment]
Closed since controlnet_aux allows batch processing.
https://raw.githubusercontent.com/Fannovel16/comfyui_controlnet_aux/main/examples/example_anyline.png

**Comment by DHG-Dav** [comment]
this problem remains in A1111 though.
